import { useEffect, useRef } from "react";

/**
 * Detects when a new build of the app has been deployed and calls onNewVersion().
 *
 * Strategy: fetch `/` (index.html) with no-store and extract the hashed asset
 * URLs that Vite embeds in <script type="module" src="/assets/index-XXXX.js">.
 * Those filenames change every build, so they are a reliable deploy signal —
 * unlike a static /version.json which would have to be regenerated by the
 * build pipeline.
 *
 * - Polls every `intervalMs` (default 60s)
 * - Re-checks immediately when the tab regains focus / visibility
 * - Falls back to /version.json if the HTML signature can't be read
 */
export function useVersionCheck(
  onNewVersion: () => void,
  intervalMs: number = 60_000,
) {
  const initialVersionRef = useRef<string | null>(null);
  const notifiedRef = useRef(false);
  const cbRef = useRef(onNewVersion);
  cbRef.current = onNewVersion;

  useEffect(() => {
    const host = window.location.hostname;
    const isPreviewOrDev =
      host.includes("id-preview--") ||
      host.includes("lovableproject.com") ||
      host === "localhost" ||
      host === "127.0.0.1";

    // Lovable preview URLs can be pinned to a specific build via query params.
    // Polling `/` without that context can look like a new deploy and cause a
    // reload loop while the user simply navigates between lazy-loaded routes.
    if (isPreviewOrDev) return;

    let cancelled = false;

    const fetchVersion = async (): Promise<string | null> => {
      // 1) Primary: hash of asset URLs in index.html (changes every build)
      try {
        const url = new URL(window.location.href);
        url.pathname = "/";
        url.searchParams.set("_v", Date.now().toString());
        const res = await fetch(url.toString(), {
          cache: "no-store",
          headers: { "Cache-Control": "no-cache", Accept: "text/html" },
        });
        if (res.ok) {
          const html = await res.text();
          // Collect every hashed asset reference (Vite emits /assets/xxx-HASH.js|.css)
          const matches = html.match(/\/assets\/[A-Za-z0-9_\-./]+\.(?:js|css)/g);
          if (matches && matches.length) {
            // Sort + join → stable signature regardless of attribute order
            return Array.from(new Set(matches)).sort().join("|");
          }
        }
      } catch {
        // fall through
      }

      // 2) Fallback: legacy /version.json
      try {
        const res = await fetch(`/version.json?t=${Date.now()}`, {
          cache: "no-store",
          headers: { "Cache-Control": "no-cache" },
        });
        if (!res.ok) return null;
        const data = await res.json();
        return typeof data?.version === "string" ? data.version : null;
      } catch {
        return null;
      }
    };

    const check = async () => {
      const v = await fetchVersion();
      if (cancelled || !v) return;
      if (initialVersionRef.current === null) {
        initialVersionRef.current = v;
        return;
      }
      if (v !== initialVersionRef.current && !notifiedRef.current) {
        notifiedRef.current = true;
        cbRef.current();
      }
    };

    // Prime the baseline immediately
    check();
    const id = window.setInterval(check, intervalMs);

    const onVis = () => {
      if (document.visibilityState === "visible") check();
    };
    document.addEventListener("visibilitychange", onVis);
    window.addEventListener("focus", onVis);

    return () => {
      cancelled = true;
      window.clearInterval(id);
      document.removeEventListener("visibilitychange", onVis);
      window.removeEventListener("focus", onVis);
    };
  }, [intervalMs]);
}
