-- REMOTE HISTORY RECEIPT (source-only catalog reconciliation).
-- Remote ledger version: 20260809004151
-- Remote ledger name: ops_floor_cashier_canonical_mutations
-- This version already exists in the linked production migration ledger.
-- The historical source is not replayable from the active catalog.
-- This comment-only file preserves local lineage metadata and MUST NOT represent a schema change.
