-- REMOTE HISTORY RECEIPT (source-only catalog reconciliation).
-- Remote ledger version: 20260807202443
-- Remote ledger name: 20270108000000_ops_operator_membership_baseline
-- This version already exists in the linked production migration ledger.
-- The historical source is not replayable from the active catalog.
-- This comment-only file preserves local lineage metadata and MUST NOT represent a schema change.
