-- REMOTE HISTORY RECEIPT (source-only catalog reconciliation).
-- Remote ledger version: 20260807190106
-- Remote ledger name: 20270107000002_close_dealer_tables_rpc_lineage_v1
-- This version already exists in the linked production migration ledger.
-- The historical source is not replayable from the active catalog.
-- This comment-only file preserves local lineage metadata and MUST NOT represent a schema change.
