-- REMOTE HISTORY RECEIPT (source-only catalog reconciliation).
-- Remote ledger version: 20260827173614
-- Remote ledger name: administrative_close_stale_dealer_attendance
-- This version already exists in the linked production migration ledger.
-- The historical source is not replayable from the active catalog.
-- This comment-only file preserves local lineage metadata and MUST NOT represent a schema change.
