// Poker IQ Drill — static hand bank (MVP 1). vi-canonical, curated content.
//
// ⚠️ DRAFT CONTENT. Every hand ships as reviewStatus:"draft" until a coach/TD
// signs it off against the approval rubric (spot realistic · baseline not
// over-dogmatic · acceptable alternatives listed · wording "trong đa số tình
// huống mặc định" not "đáp án đúng" · leak tags proportionate). The drafted
// values below were authored by an assistant and are NOT production-approved.
//
// "preferredBaseline" is a *baseline recommendation*, never an absolute correct
// answer — many spots have several acceptable lines (acceptableAlternatives).
import { CONTENT_VERSION, DrillHand } from "./types";

type RawHand = Omit<DrillHand, "contentVersion" | "reviewStatus">;

const RAW: RawHand[] = [
  // ── 1. Preflop discipline ───────────────────────────────────────────────
  {
    id: "pfd_1",
    category: "preflop_discipline",
    difficulty: "easy",
    villainProfile: "nit",
    heroHand: "K♣ J♦",
    position: "MP",
    stackBb: 40,
    scenario: "UTG (nit) raise 2.5BB. Bạn cầm KJo ở MP, stack 40BB.",
    options: [
      { id: "a", label: "Fold", score: 92 },
      { id: "b", label: "Call", score: 70 },
      { id: "c", label: "3-bet", score: 50 },
      { id: "d", label: "All-in", score: 30, leaks: ["overcall_oop"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "Trong đa số tình huống mặc định, KJo bị range UTG nit thống trị; fold giữ kỷ luật.",
    contentConfidence: "high",
    provenanceNote: "Baseline fold theo range UTG chặt; call OOP dễ bị dominate.",
  },
  {
    id: "pfd_2",
    category: "preflop_discipline",
    difficulty: "easy",
    villainProfile: "unknown",
    heroHand: "A♠ T♠",
    position: "CO",
    stackBb: 45,
    scenario: "Fold tới bạn ở CO, stack 45BB. ATs.",
    options: [
      { id: "a", label: "Raise 2.2BB", score: 90 },
      { id: "b", label: "Limp", score: 78 },
      { id: "c", label: "Fold", score: 55 },
      { id: "d", label: "All-in", score: 32, leaks: ["overcall_oop"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "ATs là hand mở chuẩn ở CO; raise lấy initiative trong đa số tình huống mặc định.",
    contentConfidence: "high",
    provenanceNote: "Open-raise baseline ở late position với suited broadway.",
  },
  {
    id: "pfd_3",
    category: "preflop_discipline",
    difficulty: "medium",
    villainProfile: "unknown",
    heroHand: "7♥ 7♣",
    position: "HJ",
    stackBb: 38,
    scenario: "Fold tới bạn ở HJ, stack 38BB. 77.",
    options: [
      { id: "a", label: "Raise 2.2BB", score: 92 },
      { id: "b", label: "Limp", score: 72 },
      { id: "c", label: "Fold", score: 52 },
      { id: "d", label: "All-in", score: 30, leaks: ["overcall_oop"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "77 đủ mạnh để open ở HJ; raise tốt hơn limp trong đa số tình huống mặc định.",
    contentConfidence: "high",
    provenanceNote: "Pocket pair mở chuẩn từ HJ tại stack trung bình.",
  },
  {
    id: "pfd_4",
    category: "preflop_discipline",
    difficulty: "medium",
    villainProfile: "aggro",
    heroHand: "A♦ 9♦",
    position: "MP",
    stackBb: 35,
    scenario: "MP, stack 35BB, A9s. CO sau bạn là aggro hay 3-bet.",
    options: [
      { id: "a", label: "Fold", score: 88 },
      { id: "b", label: "Raise 2.2BB", score: 66 },
      { id: "c", label: "Limp", score: 48 },
      { id: "d", label: "All-in", score: 30, leaks: ["overcall_oop"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "Với aggro 3-bet phía sau, A9s ở MP là open biên; fold/tighten là baseline hợp lý.",
    contentConfidence: "medium",
    provenanceNote: "Siết range MP khi có aggro 3-bettor ngay sau.",
  },

  // ── 2. Position & steal ─────────────────────────────────────────────────
  {
    id: "ps_1",
    category: "position_steal",
    difficulty: "easy",
    villainProfile: "nit",
    heroHand: "Q♠ 9♠",
    position: "BTN",
    stackBb: 32,
    scenario: "Fold tới bạn ở BTN, stack 32BB. SB/BB đều chơi chặt. Q9s.",
    options: [
      { id: "a", label: "Raise 2.2BB (steal)", score: 90 },
      { id: "b", label: "Raise 2.5BB", score: 78 },
      { id: "c", label: "Limp", score: 55 },
      { id: "d", label: "Fold", score: 34, leaks: ["tight_btn_co"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "Vị trí BTN trước blinds chặt là spot steal tốt; fold ở đây bỏ lỡ EV.",
    contentConfidence: "high",
    provenanceNote: "Steal baseline trên BTN vs blinds passive.",
  },
  {
    id: "ps_2",
    category: "position_steal",
    difficulty: "medium",
    villainProfile: "unknown",
    heroHand: "K♦ 8♦",
    position: "CO",
    stackBb: 30,
    scenario: "Fold tới bạn ở CO, stack 30BB. K8s.",
    options: [
      { id: "a", label: "Raise 2.2BB", score: 88 },
      { id: "b", label: "Raise nhỏ rồi fold vs 3-bet", score: 66 },
      { id: "c", label: "Limp", score: 50 },
      { id: "d", label: "Fold", score: 32, leaks: ["tight_btn_co"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "K8s mở được ở CO; chủ động steal trong đa số tình huống mặc định.",
    contentConfidence: "medium",
    provenanceNote: "Open-steal baseline ở CO với suited.",
  },
  {
    id: "ps_3",
    category: "position_steal",
    difficulty: "medium",
    villainProfile: "passive",
    heroHand: "T♣ 9♣",
    position: "BTN",
    stackBb: 28,
    scenario: "Fold tới bạn ở BTN, stack 28BB. T9s.",
    options: [
      { id: "a", label: "Raise 2.2BB", score: 92 },
      { id: "b", label: "Raise 2.5BB", score: 78 },
      { id: "c", label: "Limp", score: 54 },
      { id: "d", label: "Fold", score: 33, leaks: ["tight_btn_co"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "T9s là steal mạnh ở BTN nhờ playability hậu flop.",
    contentConfidence: "high",
    provenanceNote: "Suited connector steal baseline trên BTN.",
  },
  {
    id: "ps_4",
    category: "position_steal",
    difficulty: "hard",
    villainProfile: "aggro",
    heroHand: "J♥ 8♥",
    position: "CO",
    stackBb: 30,
    scenario: "CO, stack 30BB, J8s. BTN là aggro hay 3-bet light.",
    options: [
      { id: "a", label: "Raise rồi sẵn sàng đối mặt 3-bet", score: 86 },
      { id: "b", label: "Raise rồi luôn fold vs 3-bet", score: 64 },
      { id: "c", label: "Fold", score: 50, leaks: ["tight_btn_co"] },
      { id: "d", label: "Limp", score: 32 },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "Vẫn steal được nhưng cần kế hoạch vs aggro 3-bet; fold thẳng là hơi tight.",
    contentConfidence: "medium",
    provenanceNote: "Giữ steal nhưng có plan vs 3-bet thay vì over-fold.",
  },

  // ── 3. Vs aggro ─────────────────────────────────────────────────────────
  {
    id: "va_1",
    category: "vs_aggro",
    difficulty: "medium",
    villainProfile: "aggro",
    heroHand: "A♠ Q♠",
    position: "CO",
    stackBb: 38,
    scenario: "Bạn open 2.2BB ở CO. BTN (aggro) 3-bet lên 8BB. AQs, 38BB.",
    options: [
      { id: "a", label: "Call hoặc 4-bet nhỏ", score: 90 },
      { id: "b", label: "Call", score: 66 },
      { id: "c", label: "All-in", score: 50 },
      { id: "d", label: "Fold", score: 34, leaks: ["overfold_vs_aggro"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "AQs quá mạnh để fold vs aggro 3-bet; call/4-bet tùy tần suất 3-bet.",
    contentConfidence: "high",
    provenanceNote: "Không over-fold hand mạnh trước người 3-bet rộng.",
  },
  {
    id: "va_2",
    category: "vs_aggro",
    difficulty: "hard",
    villainProfile: "aggro",
    heroHand: "T♦ T♣",
    position: "MP",
    stackBb: 30,
    scenario: "Bạn open ở MP. BTN aggro 3-bet. TT, 30BB.",
    options: [
      { id: "a", label: "Jam/4-bet ship", score: 88 },
      { id: "b", label: "Call gọn rồi đánh hậu flop", score: 70 },
      { id: "c", label: "Call thụ động", score: 55 },
      { id: "d", label: "Fold", score: 32, leaks: ["overfold_vs_aggro"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "30BB với TT vs aggro 3-bet thường là spot ship; fold là quá nhược.",
    contentConfidence: "medium",
    provenanceNote: "TT 30BB vs aggro: jam baseline, không fold.",
  },
  {
    id: "va_3",
    category: "vs_aggro",
    difficulty: "hard",
    villainProfile: "aggro",
    heroHand: "A♣ J♣",
    position: "BTN",
    stackBb: 35,
    scenario: "Bạn open BTN. SB aggro 3-bet 10BB. AJs, 35BB.",
    options: [
      { id: "a", label: "Call", score: 92 },
      { id: "b", label: "4-bet nhỏ", score: 72 },
      { id: "c", label: "All-in", score: 50 },
      { id: "d", label: "Fold", score: 33, leaks: ["overfold_vs_aggro"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "AJs có position và đủ equity để call vs aggro; fold là rò rỉ rõ.",
    contentConfidence: "high",
    provenanceNote: "Call in-position vs aggro thay vì over-fold.",
  },
  {
    id: "va_4",
    category: "vs_aggro",
    difficulty: "medium",
    villainProfile: "aggro",
    heroHand: "K♥ Q♥",
    position: "HJ",
    stackBb: 33,
    scenario: "Bạn open HJ. CO aggro 3-bet. KQs, 33BB.",
    options: [
      { id: "a", label: "Call / 4-bet tùy tần suất", score: 86 },
      { id: "b", label: "Call", score: 69 },
      { id: "c", label: "All-in", score: 52 },
      { id: "d", label: "Fold", score: 30, leaks: ["overfold_vs_aggro"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "KQs giữ được vs aggro 3-bet; tiếp tục thay vì fold trong đa số tình huống mặc định.",
    contentConfidence: "medium",
    provenanceNote: "Defend KQs vs aggro 3-bet; tránh over-fold.",
  },

  // ── 4. Vs nit / passive ─────────────────────────────────────────────────
  {
    id: "vnp_1",
    category: "vs_nit_passive",
    difficulty: "medium",
    villainProfile: "nit",
    heroHand: "T♠ T♦",
    position: "HJ",
    stackBb: 45,
    scenario: "Bạn 3-bet, UTG (nit) 4-bet. TT, 45BB.",
    options: [
      { id: "a", label: "Fold", score: 92 },
      { id: "b", label: "Call set-mine cạn", score: 72 },
      { id: "c", label: "All-in", score: 50 },
      { id: "d", label: "Jam ngay", score: 34, leaks: ["spew_vs_nit"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "Range 4-bet của nit rất chặt; jam TT vào đó là spew. Fold là baseline.",
    contentConfidence: "high",
    provenanceNote: "Tôn trọng range 4-bet của nit; không overplay TT.",
  },
  {
    id: "vnp_2",
    category: "vs_nit_passive",
    difficulty: "medium",
    villainProfile: "nit",
    heroHand: "A♦ Q♠",
    position: "BTN",
    stackBb: 40,
    scenario: "UTG (nit) open, fold tới bạn BTN. AQo, 40BB.",
    options: [
      { id: "a", label: "Call / 3-bet mỏng", score: 92 },
      { id: "b", label: "Call", score: 70 },
      { id: "c", label: "Fold", score: 52 },
      { id: "d", label: "All-in", score: 32, leaks: ["spew_vs_nit"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "Có position vs nit; chơi tiếp với AQo nhưng không jam vô lý.",
    contentConfidence: "medium",
    provenanceNote: "Exploit nit bằng position, tránh over-jam.",
  },
  {
    id: "vnp_3",
    category: "vs_nit_passive",
    difficulty: "easy",
    villainProfile: "passive",
    heroHand: "9♣ 9♦",
    position: "CO",
    stackBb: 42,
    scenario: "Limper passive ở MP. Bạn cầm 99 ở CO, 42BB.",
    options: [
      { id: "a", label: "Iso-raise to ~5BB", score: 90 },
      { id: "b", label: "Raise nhỏ 4BB", score: 78 },
      { id: "c", label: "Over-limp", score: 55 },
      { id: "d", label: "Fold", score: 33, leaks: ["spew_vs_nit"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "Iso-raise để phạt limper passive và lấy initiative với 99.",
    contentConfidence: "high",
    provenanceNote: "Iso-raise baseline vs passive limper.",
  },
  {
    id: "vnp_4",
    category: "vs_nit_passive",
    difficulty: "medium",
    villainProfile: "passive",
    heroHand: "K♠ Q♦",
    position: "BTN",
    stackBb: 38,
    scenario: "MP passive open nhỏ, fold tới bạn BTN. KQo, 38BB.",
    options: [
      { id: "a", label: "3-bet mỏng / call", score: 88 },
      { id: "b", label: "Call", score: 78 },
      { id: "c", label: "Fold", score: 54 },
      { id: "d", label: "All-in", score: 30, leaks: ["spew_vs_nit"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "KQo có position vs passive; 3-bet mỏng hoặc call đều ổn, không cần jam.",
    contentConfidence: "medium",
    provenanceNote: "Khai thác passive bằng position, không overplay.",
  },

  // ── 5. Tournament pressure (ICM / bubble) ───────────────────────────────
  {
    id: "tp_1",
    category: "tournament_pressure",
    difficulty: "hard",
    villainProfile: "aggro",
    heroHand: "A♣ 9♦",
    position: "SB",
    stackBb: 18,
    scenario: "Còn 14 người, 12 ITM. Bạn 18BB ở SB, A9o. BTN chip leader open rộng.",
    options: [
      { id: "a", label: "Jam (resteal)", score: 90 },
      { id: "b", label: "Call", score: 78 },
      { id: "c", label: "Fold", score: 55 },
      { id: "d", label: "Limp", score: 34, leaks: ["resteal_15_25"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "A9o 18BB vs open rộng của chip leader là spot resteal có EV; jam baseline.",
    contentConfidence: "medium",
    provenanceNote: "Resteal jam 15–25BB vs open rộng ở bubble.",
  },
  {
    id: "tp_2",
    category: "tournament_pressure",
    difficulty: "medium",
    villainProfile: "unknown",
    heroHand: "A♠ J♣",
    position: "BTN",
    stackBb: 22,
    scenario: "Gần bubble. Bạn 22BB ở BTN, AJo, fold tới bạn.",
    options: [
      { id: "a", label: "Open-raise 2.1BB", score: 88 },
      { id: "b", label: "Open-jam", score: 78 },
      { id: "c", label: "Limp", score: 52 },
      { id: "d", label: "Fold", score: 33, leaks: ["resteal_15_25"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: ["b"],
    explanation: "AJo 22BB BTN là open chuẩn; fold là quá nhược ở vị trí mạnh.",
    contentConfidence: "high",
    provenanceNote: "Open baseline 20–25BB ở BTN gần bubble.",
  },
  {
    id: "tp_3",
    category: "tournament_pressure",
    difficulty: "hard",
    villainProfile: "nit",
    heroHand: "8♥ 8♠",
    position: "BB",
    stackBb: 16,
    scenario: "Bubble căng. UTG (nit) jam 14BB. Bạn 16BB ở BB, 88.",
    options: [
      { id: "a", label: "Cân nhắc ICM rồi call", score: 92 },
      { id: "b", label: "Call ngay", score: 70 },
      { id: "c", label: "Fold theo ICM", score: 50 },
      { id: "d", label: "Tự jam thêm", score: 32, leaks: ["resteal_15_25"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "Vs range jam chặt của nit ở bubble, cân ICM trước khi call là tư duy đúng.",
    contentConfidence: "medium",
    provenanceNote: "ICM-aware call vs nit jam ở bubble.",
  },
  {
    id: "tp_4",
    category: "tournament_pressure",
    difficulty: "medium",
    villainProfile: "aggro",
    heroHand: "K♣ T♣",
    position: "CO",
    stackBb: 20,
    scenario: "Sát final table. Bạn 20BB ở CO, KTs, fold tới bạn.",
    options: [
      { id: "a", label: "Open-raise", score: 86 },
      { id: "b", label: "Open-jam", score: 70 },
      { id: "c", label: "Limp", score: 54 },
      { id: "d", label: "Fold", score: 30, leaks: ["resteal_15_25"] },
    ],
    preferredBaseline: "a",
    acceptableAlternatives: [],
    explanation: "KTs 20BB CO là open có lời; chủ động giành chip trước final table.",
    contentConfidence: "medium",
    provenanceNote: "Open baseline 20BB CO gần final table.",
  },
];

export const DRILL_HANDS: DrillHand[] = RAW.map((h) => ({
  ...h,
  contentVersion: CONTENT_VERSION,
  reviewStatus: "draft",
}));

/** True only when EVERY hand has passed coach/TD review. Gates production use. */
export const ALL_CONTENT_APPROVED: boolean = DRILL_HANDS.every(
  (h) => h.reviewStatus === "approved",
);
