tree 4bf106f0a982fd7e597e0936b02b81eb81b37a13

.claude/
.github/
.gitignore
.grok/
.omo/
.opencode/
AGENTS.md
ALL_SESSIONS_REDEPLOY_BRIEF.md
CLAUDE.md
CODEX_REVIEW_PACKET_swing-schedule-payroll.md
Huong-dan-su-dung-Dealer-Swing.pdf
INTEGRATION_REPORTS/
VBacker/
VinPoker/
_APPLY-FNB-SQL/
a1a-toprow-fix-portrait.png
backups/
c3-feltv2-landscape-on.png
card-reissue-preview.png
codegraph_test.txt
codegraph_test_err.txt
cols-9max.png
deliverables/
deploy-package/
docs/
drill-case1-flagOFF-old-panel.png
drill-case1-flagON-engine-panel.png
drill-case2-preview-duKien.png
felt-landscape-mobile-fit.png
felt-landscape-mobile-fit2.png
felt-landscape-mobile-fit560.png
graphify-out/
ios-audit-landing-390.png
ios-ops-alerts-390.png
ios-ops-more-390.png
ios-ops-tables-390.png
ios-ops-today-390.png
ios-ops-today-430.png
ios-ops-today-768.png
ios-ops-tournaments-390.png
ios2-alerts-390.png
ios2-more-390.png
ios2-table-sheet-390.png
ios2-tables-390.png
ios2-today-390.png
ios2-tournaments-390.png
lf-phase2-9max.png
lf-sanity-9max.png
livefelt-after.png
livefelt-before.png
livefelt-fullboard-after.png
livefelt-preflop-after.png
livefelt-preflop-final.png
node_modules/
output/
poker-engine-codex-pack.md
poker-engine-codex-pack.md.new
portrait-after.png
portrait-before.png
rpt-desktop-1440.png
rpt-feed-state.png
rpt-mobile-replayer.png
rpt-reference-mobile.png
rpt-replayer-start.png
rpt-step2.png
scripts/
set1-a1-tournaments.png
set1-a2-sheet.png
set1-b1-tables.png
set1-b2-tablesheet.png
set1-s1-cockpit.png
set1-s4-levels.png
set1-s7-playersheet.png
set1-s8-playerinfo.png
set2-d1-tables.png
set2-d2-swing-sheet.png
set2-d3-dealer-pool.png
set2-d4-dealer-sheet.png
set2-d5-staffing.png
set2-d6-close-shift.png
set2-d6-close-unlocked.png
set2-p1-pick-dealer.png
set2-p2-checkin.png
set3-f1-orders.png
set3-f2-payment.png
set3-f2-restate-confirm.png
set3-p3-create.png
set3-p4-kitchen.png
set3-p5-shift.png
set3-r4-qr.png
set3-r5-stock.png
set4-c1-overview.png
set4-c2-vault.png
set4-m1-posts.png
set4-m2-actions.png
set4-p6-compose-filled.png
set4-p6-compose.png
set4-p6-publish-confirm.png
set4-r2-colorup.png
set4-r2-restate.png
set4-r3-bag.png
set5-ac1-recon.png
set5-ac2-alerts.png
set5-si1-report.png
set5-si2-decide.png
set5-si2-picker.png
set5-t1-contribution.png
set5-t1-finance.png
set5-t2-events.png
set6-q1-queue.png
set6-q2-regsheet.png
set6-q3-buyin.png
set6-q3-restate.png
set6-q4-sepay.png
set6-q5-staking.png
set6-q6-verify.png
skills-lock.json
stack-3max-closeup.png
stack-9max-landscape.png
stack-9max-portrait.png
supabase/
tmp-dealer-mobile-app
tmp/
ui-forecast-panel.jpeg
ui-overlay-forecast-mode.jpeg
ui-overview-with-avg-tile.jpeg
ui-quarterly-breakdown.jpeg
vinpoker-contaminated-untracked-backup-20260611/
vinpoker-stage3h-untracked-backup-20260611/
wire-floor-loggedout-guard.png
wire-swing-board.png
wire-swing-dealers.png
wire-swing-staff.png
wire-tournaments-list.png
worktrees/
