import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {atomicSql,loadMigration,dependencyPredicate} from './dealer-policy-57-protected-apply.mjs';
import {receiptSql} from './floor-37-47-protected-apply.mjs';
test('PG17 policy57 receipt failure rolls back definition and success/replay fenced',
 {skip:process.env.POLICY57_PG_TEST!=='1'},()=>{
 assert.equal(process.env.PGHOST,'127.0.0.1');assert.equal(process.env.PGUSER,'postgres');
 assert.equal(process.env.PGDATABASE,'vinpoker_ops_policy57_atomic_20261011');
 for(const key of ['PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS'])assert.ok(!process.env[key]);
 const query=sql=>spawnSync('psql',['-X','-qAt','-v','ON_ERROR_STOP=1'],{input:sql,encoding:'utf8'});
 const check=sql=>{const r=query(sql);assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
 assert.equal(check("SELECT current_user='postgres' AND current_setting('server_version_num')::int BETWEEN 170000 AND 179999 AND to_regclass('supabase_migrations.schema_migrations') IS NULL;"),'t');
 const schema=readFileSync(resolve(process.env.SCHEMA_ARTIFACT_DIR,'live-public-schema.sql'),'utf8');
 assert.equal(createHash('sha256').update(schema).digest('hex'),'d23cfa75a7381453ba0d6216346f6460c816a3b1525ef5d47984c3a995ddc56a');
 const start=schema.indexOf('CREATE OR REPLACE FUNCTION "public"."set_dealer_pt_wage_accrual_policy"(');
 assert.ok(start>=0);const body=schema.indexOf('AS $$',start),end=schema.indexOf('$$;',body+5);
 assert.ok(body>start&&end>body);check(schema.slice(start,end+3));
 assert.equal(check(`SELECT ${dependencyPredicate()};`),'t');
 const snapshot="SELECT jsonb_build_object('definition',pg_get_functiondef(p.oid),'owner',p.proowner,'acl',p.proacl,'config',p.proconfig)::text FROM pg_proc p WHERE p.oid='public.set_dealer_pt_wage_accrual_policy(uuid,boolean,timestamptz,text)'::regprocedure;";
 const before=check(snapshot);
 check(`CREATE SCHEMA supabase_migrations;CREATE TABLE supabase_migrations.schema_migrations(version text PRIMARY KEY,name text,statements text[]);
 CREATE FUNCTION public.reject57_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.version='20270128000057' THEN RAISE EXCEPTION 'injected57_receipt_failure';END IF;RETURN NEW;END $$;
 CREATE TRIGGER reject57 BEFORE INSERT ON supabase_migrations.schema_migrations FOR EACH ROW EXECUTE FUNCTION public.reject57_receipt();`);
 const failed=query(atomicSql());assert.notEqual(failed.status,0);assert.match(failed.stderr,/injected57_receipt_failure/);
 assert.equal(check(snapshot),before);
 assert.deepEqual(JSON.parse(check(receiptSql(loadMigration()))),{count:0,exact:false});
 check('DROP TRIGGER reject57 ON supabase_migrations.schema_migrations;DROP FUNCTION public.reject57_receipt();');
 check(atomicSql());
 check(readFileSync(new URL('../../tests/dealerSwing/accrualTenant.readonly-postcheck.sql',import.meta.url),'utf8'));
 assert.deepEqual(JSON.parse(check(receiptSql(loadMigration()))),{count:1,exact:true});
 const applied=check(snapshot),replay=query(atomicSql());
 assert.notEqual(replay.status,0);assert.match(replay.stderr,/policy57_precondition_drift/);
 assert.equal(check(snapshot),applied);
 assert.deepEqual(JSON.parse(check(receiptSql(loadMigration()))),{count:1,exact:true});
 console.log('POLICY57_ATOMIC_ROLLBACK_RECEIPT_OBJECT_REPLAY_PASS');
});
