import {
  SCHEDULE_EVIDENCE_QUALITY,
  type ScheduleEvidenceSource,
  type ScheduleFieldKey,
  type ScheduleGtdInput,
  type ScheduleMissingReason,
  type ScheduleSeedEvent,
} from "./vietnamScheduleSupply";

export const VIETNAM_SCHEDULE_SUPPLY_V1_SOURCE_CUTOFF = "2026-07-28T14:05:00.000Z";

export const VIETNAM_SCHEDULE_SUPPLY_V1_SOURCES: readonly ScheduleEvidenceSource[] = [
  {
    sourceId: "rpt-sep-11-12-2026",
    posterIdentity: "rpt",
    sourcePath: "docs/series/evidence/vietnam/inbox/rpt_schedule_sep_11_12_2026.png",
    sourceSha256: "2d70ed4cb17e6915753e60908b0c18a9f8aeb57362335b7f40b35a5c07cd4e11",
    sourceByteLength: "719976",
    widthPixels: "730",
    heightPixels: "734",
    organizer: "RPT",
    venue: null,
    seriesName: "RPT September Schedule",
    city: null,
    country: "Vietnam",
    market: "vietnam",
    displayedScheduleDates: ["2026-09-11", "2026-09-12"],
    evidenceQuality: SCHEDULE_EVIDENCE_QUALITY,
  },
  {
    sourceId: "center-p-jul-17-2026",
    posterIdentity: "center_p",
    sourcePath: "docs/series/evidence/vietnam/inbox/center_p_schedule_jul_17_2026.png",
    sourceSha256: "ae86830b97335debcf88e480bc0cf20572426af76ae8456aa2108e88da602cca",
    sourceByteLength: "869499",
    widthPixels: "729",
    heightPixels: "730",
    organizer: "Center-P Poker Masters",
    venue: "Center-P",
    seriesName: "Center-P Poker Master Season 2",
    city: null,
    country: "Vietnam",
    market: "vietnam",
    displayedScheduleDates: ["2026-07-17"],
    evidenceQuality: SCHEDULE_EVIDENCE_QUALITY,
  },
  {
    sourceId: "grand-loyal-jul-29-2026",
    posterIdentity: "grand_loyal",
    sourcePath: "docs/series/evidence/vietnam/inbox/grand_loyal_schedule_jul_29_2026.png",
    sourceSha256: "999c86b0f2496166683240dfccf774d574d675073580e022e9c465a513fa7bb4",
    sourceByteLength: "501566",
    widthPixels: "738",
    heightPixels: "686",
    organizer: "Grand Loyal Poker Club",
    venue: "Grand Loyal Poker Club",
    seriesName: "Grand Loyal Poker Championship V",
    city: "Hanoi",
    country: "Vietnam",
    market: "vietnam",
    displayedScheduleDates: ["2026-07-29"],
    evidenceQuality: SCHEDULE_EVIDENCE_QUALITY,
  },
];

type RowInput = Pick<
  ScheduleSeedEvent,
  | "eventKey"
  | "competitionKey"
  | "sourceId"
  | "scheduleDate"
  | "localStartTime"
  | "eventName"
  | "eventFamily"
  | "gtd"
  | "visualRegion"
> & Partial<Omit<
  ScheduleSeedEvent,
  | "eventKey"
  | "competitionKey"
  | "sourceId"
  | "scheduleDate"
  | "localStartTime"
  | "eventName"
  | "eventFamily"
  | "gtd"
  | "visualRegion"
>>;

const HEADER_REGIONS: Readonly<Partial<Record<ScheduleFieldKey, string>>> = {
  market: "owner-supplied-vietnam-release-scope",
  country: "owner-supplied-vietnam-release-scope",
  city: "poster-header",
  venue: "poster-header",
  organizer: "poster-header",
  series_name: "poster-header",
};

function row(input: RowInput): ScheduleSeedEvent {
  const { fieldRegions, ...overrides } = input;
  return {
    dayFlightIdentity: null,
    eventNumber: null,
    game: "NLH",
    currency: "VND",
    totalBuyInMinorUnits: null,
    prizeContributionMinorUnits: null,
    organizerFeeMinorUnits: null,
    staffFeeBps: null,
    startingStack: null,
    levelDurationMinutes: [],
    registrationCloseLevel: null,
    registrationCloseTime: null,
    itmStatement: null,
    playToStatement: null,
    satelliteLinkage: null,
    promotionNote: null,
    floor: null,
    missingReasons: {},
    uncertainFields: [],
    ownerContextFields: ["market", "country"],
    conflictingFields: [],
    ...overrides,
    fieldRegions: {
      ...HEADER_REGIONS,
      ...fieldRegions,
    },
  };
}

function monetaryGtd(minorUnits: string): ScheduleGtdInput {
  return { type: "monetary", minorUnits, currency: "VND", scale: 0 };
}

function seats(quantity: string): ScheduleGtdInput {
  return { type: "seats", quantity };
}

function tickets(quantity: string): ScheduleGtdInput {
  return { type: "tickets", quantity };
}

function missingGtd(reason: ScheduleMissingReason = "dash_displayed"): ScheduleGtdInput {
  return { type: "missing", reason };
}

const RPT_SOURCE = "rpt-sep-11-12-2026";
const CENTER_SOURCE = "center-p-jul-17-2026";
const GRAND_SOURCE = "grand-loyal-jul-29-2026";
const CENTER_STAFF_FEE_REGION = "poster-footer-note-3-percent-staff-fee";
const GRAND_STAFF_FEE_REGION = "poster-footer-note-3-percent-staff-fee";
const GRAND_GENERAL_PROMOTION = "First 5 players to register before Level 1 receive 50% rake off.";

export const VIETNAM_SCHEDULE_SUPPLY_V1_EVENTS: readonly ScheduleSeedEvent[] = [
  row({
    eventKey: "rpt-d1-s1-opener-satellite",
    competitionKey: "rpt-d1-s1-opener-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "10:00",
    eventNumber: "S1",
    eventName: "Satellite to RPT Opener Event - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "800000",
    gtd: seats("3"),
    startingStack: "8000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "11:34",
    satelliteLinkage: "RPT Opener Event - 1 in 10",
    visualRegion: "day-1-row-s1",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-s2-high-roller-opener-satellite",
    competitionKey: "rpt-d1-s2-high-roller-opener-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "10:30",
    eventNumber: "S2",
    eventName: "Satellite to RPT High Roller Opener - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "2500000",
    gtd: missingGtd(),
    startingStack: "12000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "12:04",
    satelliteLinkage: "RPT High Roller Opener - 1 in 10",
    visualRegion: "day-1-row-s2",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-opener-day-1a",
    competitionKey: "rpt-opener-event",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "10:30",
    dayFlightIdentity: "Day 1A",
    eventNumber: "1",
    eventName: "RPT Opener Event - Day 1A",
    eventFamily: "kick_off",
    totalBuyInMinorUnits: "6600000",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "12",
    registrationCloseTime: "16:35",
    itmStatement: "14% ITM",
    playToStatement: "Play to 10% ITM",
    visualRegion: "day-1-row-1-day-1a",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-high-roller-opener-day-1",
    competitionKey: "rpt-high-roller-opener",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "12:00",
    dayFlightIdentity: "Day 1",
    eventNumber: "2",
    eventName: "RPT High Roller Opener",
    eventFamily: "high_roller",
    totalBuyInMinorUnits: "22000000",
    gtd: monetaryGtd("2000000000"),
    startingStack: "100000",
    levelDurationMinutes: ["35", "30"],
    registrationCloseLevel: "12",
    registrationCloseTime: "19:00",
    playToStatement: "Play to final table",
    visualRegion: "day-1-row-2",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-deepstack-turbo",
    competitionKey: "rpt-event-3-deepstack-turbo",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "15:00",
    eventNumber: "3",
    eventName: "RPT Deepstack Turbo",
    eventFamily: "deepstack_turbo",
    totalBuyInMinorUnits: "2300000",
    gtd: monetaryGtd("60000000"),
    startingStack: "40000",
    levelDurationMinutes: ["20"],
    registrationCloseLevel: "8",
    registrationCloseTime: "17:35",
    visualRegion: "day-1-row-3",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-opener-day-1b",
    competitionKey: "rpt-opener-event",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "16:30",
    dayFlightIdentity: "Day 1B",
    eventNumber: "1",
    eventName: "RPT Opener Event - Day 1B",
    eventFamily: "kick_off",
    totalBuyInMinorUnits: "6600000",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "12",
    registrationCloseTime: "22:35",
    itmStatement: "14% ITM",
    playToStatement: "Play to 10% ITM",
    visualRegion: "day-1-row-1-day-1b",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-mini-deepstack",
    competitionKey: "rpt-event-4-mini-deepstack",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "17:00",
    eventNumber: "4",
    eventName: "RPT Mini Deepstack",
    eventFamily: "mini_deepstack",
    totalBuyInMinorUnits: "4500000",
    gtd: monetaryGtd("120000000"),
    startingStack: "40000",
    levelDurationMinutes: ["25", "20"],
    registrationCloseLevel: "10",
    registrationCloseTime: "21:05",
    itmStatement: "25% ITM",
    visualRegion: "day-1-row-4",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-mini-high-roller",
    competitionKey: "rpt-event-5-mini-high-roller",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "19:00",
    eventNumber: "5",
    eventName: "RPT Mini High Roller",
    eventFamily: "mini_high_roller",
    totalBuyInMinorUnits: "11000000",
    gtd: monetaryGtd("200000000"),
    startingStack: "100000",
    levelDurationMinutes: ["25", "15"],
    registrationCloseLevel: "11",
    registrationCloseTime: "23:05",
    visualRegion: "day-1-row-5",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-s3-main-event-satellite",
    competitionKey: "rpt-d1-s3-main-event-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "20:00",
    eventNumber: "S3",
    eventName: "Satellite to RPT Main Event - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "3100000",
    gtd: seats("1"),
    startingStack: "12000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "21:34",
    satelliteLinkage: "RPT Main Event - 1 in 10",
    visualRegion: "day-1-row-s3",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-s4-credit-ticket-satellite",
    competitionKey: "rpt-d1-s4-credit-ticket-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "21:00",
    eventNumber: "S4",
    eventName: "Satellite for 20M Credit Ticket - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "2300000",
    gtd: tickets("1"),
    startingStack: "10000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "22:34",
    satelliteLinkage: "20M Credit Ticket - 1 in 10",
    visualRegion: "day-1-row-s4",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-relax-event",
    competitionKey: "rpt-event-6-relax",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "21:30",
    eventNumber: "6",
    eventName: "RPT Relax Event",
    eventFamily: "relax",
    totalBuyInMinorUnits: "1800000",
    gtd: monetaryGtd("15000000"),
    startingStack: "40000",
    levelDurationMinutes: ["20", "15"],
    registrationCloseLevel: "7",
    registrationCloseTime: "23:35",
    itmStatement: "25% ITM",
    visualRegion: "day-1-row-6",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d1-happy-night",
    competitionKey: "rpt-event-7-happy-night",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-11",
    localStartTime: "23:30",
    eventNumber: "7",
    eventName: "RPT Happy Night",
    eventFamily: "happy_night",
    totalBuyInMinorUnits: "2300000",
    gtd: monetaryGtd("12000000"),
    startingStack: "40000",
    levelDurationMinutes: ["15", "10"],
    registrationCloseLevel: "5",
    registrationCloseTime: "00:40",
    itmStatement: "25% ITM",
    visualRegion: "day-1-row-7",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-s5-opener-satellite",
    competitionKey: "rpt-d2-s5-opener-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "10:00",
    eventNumber: "S5",
    eventName: "Satellite to RPT Opener Event - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "800000",
    gtd: seats("3"),
    startingStack: "8000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "11:34",
    satelliteLinkage: "RPT Opener Event - 1 in 10",
    visualRegion: "day-2-row-s5",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-opener-day-1c",
    competitionKey: "rpt-opener-event",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "10:00",
    dayFlightIdentity: "Day 1C",
    eventNumber: "1",
    eventName: "RPT Opener Event - Day 1C",
    eventFamily: "kick_off",
    totalBuyInMinorUnits: "6600000",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "12",
    registrationCloseTime: "16:05",
    itmStatement: "14% ITM",
    playToStatement: "Play to 10% ITM",
    visualRegion: "day-2-row-1-day-1c",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-s6-high-roller-deepstack-satellite",
    competitionKey: "rpt-d2-s6-high-roller-deepstack-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "10:30",
    eventNumber: "S6",
    eventName: "Satellite to RPT High Roller Deepstack - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "3700000",
    gtd: missingGtd(),
    startingStack: "12000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "12:04",
    satelliteLinkage: "RPT High Roller Deepstack - 1 in 10",
    visualRegion: "day-2-row-s6",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-high-roller-opener-final-table",
    competitionKey: "rpt-high-roller-opener",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "12:00",
    dayFlightIdentity: "Final Table",
    eventNumber: "2",
    eventName: "RPT High Roller Opener - Final Table",
    eventFamily: "high_roller",
    gtd: monetaryGtd("2000000000"),
    levelDurationMinutes: ["35"],
    playToStatement: "Final Table",
    visualRegion: "day-2-row-2-final-table",
    ownerContextFields: ["market", "country", "schedule_date"],
    missingReasons: {
      total_buy_in: "dash_displayed",
      starting_stack: "dash_displayed",
      registration_close_level: "not_applicable",
      registration_close_time: "not_applicable",
    },
  }),
  row({
    eventKey: "rpt-d2-high-roller-deepstack",
    competitionKey: "rpt-event-8-high-roller-deepstack",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "12:00",
    eventNumber: "8",
    eventName: "RPT High Roller Deepstack",
    eventFamily: "high_roller",
    totalBuyInMinorUnits: "33000000",
    gtd: monetaryGtd("1500000000"),
    startingStack: "200000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "12",
    registrationCloseTime: "18:05",
    visualRegion: "day-2-row-8",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-no-limit-holdem-8-max",
    competitionKey: "rpt-event-9-no-limit-holdem",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "13:00",
    eventNumber: "9",
    eventName: "No Limit Holdem (8-Max)",
    eventFamily: "no_limit_holdem",
    totalBuyInMinorUnits: "6600000",
    gtd: missingGtd(),
    startingStack: "40000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "10",
    registrationCloseTime: "18:00",
    visualRegion: "day-2-row-9",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-deepstack-turbo",
    competitionKey: "rpt-event-10-deepstack-turbo",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "15:00",
    eventNumber: "10",
    eventName: "RPT Deepstack Turbo",
    eventFamily: "deepstack_turbo",
    totalBuyInMinorUnits: "2300000",
    gtd: monetaryGtd("60000000"),
    startingStack: "40000",
    levelDurationMinutes: ["20"],
    registrationCloseLevel: "8",
    registrationCloseTime: "17:35",
    visualRegion: "day-2-row-10",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-opener-day-1d",
    competitionKey: "rpt-opener-event",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "16:00",
    dayFlightIdentity: "Day 1D",
    eventNumber: "1",
    eventName: "RPT Opener Event - Day 1D",
    eventFamily: "kick_off",
    totalBuyInMinorUnits: "6600000",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "12",
    registrationCloseTime: "22:05",
    itmStatement: "14% ITM",
    playToStatement: "Play to 10% ITM",
    visualRegion: "day-2-row-1-day-1d",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-mini-deepstack",
    competitionKey: "rpt-event-11-mini-deepstack",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "17:00",
    eventNumber: "11",
    eventName: "RPT Mini Deepstack",
    eventFamily: "mini_deepstack",
    totalBuyInMinorUnits: "4500000",
    gtd: monetaryGtd("120000000"),
    startingStack: "40000",
    levelDurationMinutes: ["25", "20"],
    registrationCloseLevel: "10",
    registrationCloseTime: "21:05",
    itmStatement: "25% ITM",
    visualRegion: "day-2-row-11",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-mini-high-roller",
    competitionKey: "rpt-event-12-mini-high-roller",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "19:00",
    eventNumber: "12",
    eventName: "RPT Mini High Roller",
    eventFamily: "mini_high_roller",
    totalBuyInMinorUnits: "11000000",
    gtd: monetaryGtd("200000000"),
    startingStack: "100000",
    levelDurationMinutes: ["25", "15"],
    registrationCloseLevel: "11",
    registrationCloseTime: "23:05",
    visualRegion: "day-2-row-12",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-s7-main-event-satellite",
    competitionKey: "rpt-d2-s7-main-event-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "20:00",
    eventNumber: "S7",
    eventName: "Satellite to RPT Main Event - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "3100000",
    gtd: seats("1"),
    startingStack: "12000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "21:34",
    satelliteLinkage: "RPT Main Event - 1 in 10",
    visualRegion: "day-2-row-s7",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-s8-credit-ticket-satellite",
    competitionKey: "rpt-d2-s8-credit-ticket-satellite",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "21:00",
    eventNumber: "S8",
    eventName: "Satellite for 20M Credit Ticket - 1 in 10",
    eventFamily: "satellite",
    totalBuyInMinorUnits: "2300000",
    gtd: tickets("1"),
    startingStack: "10000",
    levelDurationMinutes: ["12", "10"],
    registrationCloseLevel: "8",
    registrationCloseTime: "22:34",
    satelliteLinkage: "20M Credit Ticket - 1 in 10",
    visualRegion: "day-2-row-s8",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-opener-day-1e",
    competitionKey: "rpt-opener-event",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "21:30",
    dayFlightIdentity: "Day 1E",
    eventNumber: "1",
    eventName: "RPT Opener Event - Day 1E",
    eventFamily: "kick_off",
    totalBuyInMinorUnits: "6600000",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["15"],
    registrationCloseLevel: "8",
    registrationCloseTime: "00:40",
    itmStatement: "14% ITM",
    playToStatement: "Play to 10% ITM",
    visualRegion: "day-2-row-1-day-1e",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-relax-event",
    competitionKey: "rpt-event-13-relax",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "21:30",
    eventNumber: "13",
    eventName: "RPT Relax Event",
    eventFamily: "relax",
    totalBuyInMinorUnits: "1800000",
    gtd: monetaryGtd("15000000"),
    startingStack: "40000",
    levelDurationMinutes: ["20", "15"],
    registrationCloseLevel: "7",
    registrationCloseTime: "23:35",
    itmStatement: "25% ITM",
    visualRegion: "day-2-row-13",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),
  row({
    eventKey: "rpt-d2-happy-night",
    competitionKey: "rpt-event-14-happy-night",
    sourceId: RPT_SOURCE,
    scheduleDate: "2026-09-12",
    localStartTime: "23:30",
    eventNumber: "14",
    eventName: "RPT Happy Night",
    eventFamily: "happy_night",
    totalBuyInMinorUnits: "2300000",
    gtd: monetaryGtd("12000000"),
    startingStack: "40000",
    levelDurationMinutes: ["15", "10"],
    registrationCloseLevel: "5",
    registrationCloseTime: "00:40",
    itmStatement: "25% ITM",
    visualRegion: "day-2-row-14",
    ownerContextFields: ["market", "country", "schedule_date"],
  }),

  row({
    eventKey: "center-p-satellite-kick-off",
    competitionKey: "center-p-satellite-kick-off",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "10:00",
    eventName: "Satellite to CPM Kick-Off",
    eventFamily: "satellite",
    prizeContributionMinorUnits: "825000",
    organizerFeeMinorUnits: "125000",
    gtd: tickets("4"),
    startingStack: "8000",
    levelDurationMinutes: ["12"],
    registrationCloseLevel: "8",
    registrationCloseTime: "11:39",
    satelliteLinkage: "CPM Kick-Off",
    visualRegion: "day-2-row-10-00",
  }),
  row({
    eventKey: "center-p-kick-off-day-1c",
    competitionKey: "center-p-kick-off",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "10:30",
    dayFlightIdentity: "Day 1C",
    eventName: "CPM Kick-Off Day 1C",
    eventFamily: "kick_off",
    prizeContributionMinorUnits: "6000000",
    organizerFeeMinorUnits: "600000",
    staffFeeBps: "300",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30"],
    registrationCloseLevel: "12",
    registrationCloseTime: "16:35",
    itmStatement: "15% ITM",
    playToStatement: "Play to 12.5%",
    visualRegion: "day-2-row-10-30",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "center-p-high-roller-eagle-eye",
    competitionKey: "center-p-high-roller-eagle-eye",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "11:30",
    eventNumber: "6",
    eventName: "CPM High Roller Eagle Eye",
    eventFamily: "high_roller",
    prizeContributionMinorUnits: "30000000",
    organizerFeeMinorUnits: "3000000",
    staffFeeBps: "300",
    gtd: monetaryGtd("1500000000"),
    startingStack: "100000",
    levelDurationMinutes: ["30"],
    registrationCloseLevel: "13",
    registrationCloseTime: "18:05",
    playToStatement: "Final Table",
    promotionNote: "Discount 50% rake for 10 players to register before start.",
    visualRegion: "day-2-row-11-30",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "center-p-satellite-high-roller-eagle-eye",
    competitionKey: "center-p-satellite-high-roller-eagle-eye",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "12:00",
    eventName: "Satellite to High Roller Eagle Eye",
    eventFamily: "satellite",
    prizeContributionMinorUnits: "4125000",
    organizerFeeMinorUnits: "475000",
    gtd: tickets("1"),
    startingStack: "8000",
    levelDurationMinutes: ["12"],
    registrationCloseLevel: "8",
    registrationCloseTime: "13:39",
    satelliteLinkage: "CPM High Roller Eagle Eye",
    visualRegion: "day-2-row-12-00",
  }),
  row({
    eventKey: "center-p-kick-off-day-1d",
    competitionKey: "center-p-kick-off",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "16:30",
    dayFlightIdentity: "Day 1D",
    eventName: "CPM Kick-Off Day 1D",
    eventFamily: "kick_off",
    prizeContributionMinorUnits: "6000000",
    organizerFeeMinorUnits: "600000",
    staffFeeBps: "300",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30"],
    registrationCloseLevel: "12",
    registrationCloseTime: "22:35",
    itmStatement: "15% ITM",
    playToStatement: "Play to 12.5%",
    visualRegion: "day-2-row-16-30",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "center-p-mini-deepstack",
    competitionKey: "center-p-event-7-mini-deepstack",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "17:00",
    eventNumber: "7",
    eventName: "CPM Mini Deepstack",
    eventFamily: "mini_deepstack",
    prizeContributionMinorUnits: "3000000",
    organizerFeeMinorUnits: "300000",
    staffFeeBps: "300",
    gtd: monetaryGtd("100000000"),
    startingStack: "40000",
    levelDurationMinutes: ["25"],
    registrationCloseLevel: "10",
    registrationCloseTime: "21:10",
    itmStatement: "25% ITM",
    visualRegion: "day-2-row-17-00",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "center-p-mini-high-roller",
    competitionKey: "center-p-event-8-mini-high-roller",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "18:30",
    eventNumber: "8",
    eventName: "CPM Mini Highroller",
    eventFamily: "mini_high_roller",
    prizeContributionMinorUnits: "10000000",
    organizerFeeMinorUnits: "1000000",
    staffFeeBps: "300",
    gtd: monetaryGtd("200000000"),
    startingStack: "100000",
    levelDurationMinutes: ["25", "20"],
    registrationCloseLevel: "10",
    registrationCloseTime: "22:40",
    visualRegion: "day-2-row-18-30",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "center-p-satellite-mini-main",
    competitionKey: "center-p-satellite-mini-main",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "20:00",
    eventName: "Satellite to CPM Mini Main",
    eventFamily: "satellite",
    prizeContributionMinorUnits: "1375000",
    organizerFeeMinorUnits: "225000",
    gtd: tickets("2"),
    startingStack: "8000",
    levelDurationMinutes: ["12"],
    registrationCloseLevel: "8",
    registrationCloseTime: "21:39",
    satelliteLinkage: "CPM Mini Main",
    visualRegion: "day-2-row-20-00",
  }),
  row({
    eventKey: "center-p-after-dark",
    competitionKey: "center-p-event-9-after-dark",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "21:00",
    eventNumber: "9",
    eventName: "CPM After Dark",
    eventFamily: "after_dark",
    prizeContributionMinorUnits: "2000000",
    organizerFeeMinorUnits: "300000",
    staffFeeBps: "300",
    gtd: monetaryGtd("30000000"),
    startingStack: "30000",
    levelDurationMinutes: ["20", "15"],
    registrationCloseLevel: "10",
    registrationCloseTime: "23:15",
    itmStatement: "25% ITM",
    visualRegion: "day-2-row-21-00",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "center-p-kick-off-day-1e-turbo",
    competitionKey: "center-p-kick-off",
    sourceId: CENTER_SOURCE,
    scheduleDate: "2026-07-17",
    localStartTime: "21:30",
    dayFlightIdentity: "Day 1E Turbo",
    eventName: "CPM Kick-Off Day 1E Turbo",
    eventFamily: "kick_off",
    prizeContributionMinorUnits: "6000000",
    organizerFeeMinorUnits: "600000",
    staffFeeBps: "300",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["20", "15"],
    registrationCloseLevel: "12",
    registrationCloseTime: "01:45",
    itmStatement: "15% ITM",
    playToStatement: "Play to 12.5%",
    visualRegion: "day-2-row-21-30",
    fieldRegions: { staff_fee_bps: CENTER_STAFF_FEE_REGION },
  }),

  row({
    eventKey: "grand-loyal-s1-mega-satellite-kick-off",
    competitionKey: "grand-loyal-s1-mega-satellite-kick-off",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "09:30",
    eventNumber: "S1",
    eventName: "Mega Satellite - GTD Kick Off Event",
    eventFamily: "satellite",
    prizeContributionMinorUnits: "660000",
    organizerFeeMinorUnits: "140000",
    gtd: seats("10"),
    startingStack: "10000",
    levelDurationMinutes: ["15", "12"],
    registrationCloseLevel: "8",
    registrationCloseTime: "11:25",
    satelliteLinkage: "Madness GTD Kick Off Event",
    promotionNote: GRAND_GENERAL_PROMOTION,
    floor: "Level 2",
    visualRegion: "day-1-row-s1",
  }),
  row({
    eventKey: "grand-loyal-madness-kick-off-day-1a",
    competitionKey: "grand-loyal-madness-kick-off",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "10:00",
    dayFlightIdentity: "Day 1A",
    eventNumber: "1",
    eventName: "Madness GTD Kick Off Event - Day 1A",
    eventFamily: "kick_off",
    prizeContributionMinorUnits: "6000000",
    organizerFeeMinorUnits: "600000",
    staffFeeBps: "300",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30"],
    registrationCloseLevel: "11",
    registrationCloseTime: "15:30",
    itmStatement: "15% ITM",
    playToStatement: "Play 12.5% Day 2",
    promotionNote: `${GRAND_GENERAL_PROMOTION} Bonus chip leader 20M from prize pool.`,
    floor: "Level 3",
    visualRegion: "day-1-row-1-day-1a",
    fieldRegions: { staff_fee_bps: GRAND_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "grand-loyal-high-roller-warm-up",
    competitionKey: "grand-loyal-event-2-high-roller-warm-up",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "11:30",
    eventNumber: "2",
    eventName: "High Roller Warm Up Massive GTD",
    eventFamily: "high_roller",
    prizeContributionMinorUnits: "30000000",
    organizerFeeMinorUnits: "3000000",
    staffFeeBps: "300",
    gtd: monetaryGtd("2000000000"),
    startingStack: "100000",
    levelDurationMinutes: ["40"],
    registrationCloseLevel: "12",
    registrationCloseTime: "19:30",
    playToStatement: "Play to final table",
    promotionNote: "First 12 players to register before Level 1 receive 50% rake off.",
    floor: "Level 2",
    visualRegion: "day-1-row-2",
    fieldRegions: { staff_fee_bps: GRAND_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "grand-loyal-madness-kick-off-day-1b",
    competitionKey: "grand-loyal-madness-kick-off",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "15:00",
    dayFlightIdentity: "Day 1B",
    eventNumber: "1",
    eventName: "Madness GTD Kick Off Event - Day 1B",
    eventFamily: "kick_off",
    prizeContributionMinorUnits: "6000000",
    organizerFeeMinorUnits: "600000",
    staffFeeBps: "300",
    gtd: monetaryGtd("6000000000"),
    startingStack: "30000",
    levelDurationMinutes: ["30", "25"],
    registrationCloseLevel: "11",
    registrationCloseTime: "20:30",
    itmStatement: "15% ITM",
    playToStatement: "Play 12.5% Day 2",
    promotionNote: `${GRAND_GENERAL_PROMOTION} Bonus chip leader 20M from prize pool.`,
    floor: "Level 3",
    visualRegion: "day-1-row-1-day-1b",
    fieldRegions: { staff_fee_bps: GRAND_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "grand-loyal-superstack",
    competitionKey: "grand-loyal-event-3-superstack",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "16:00",
    eventNumber: "3",
    eventName: "Superstack",
    eventFamily: "superstack",
    prizeContributionMinorUnits: "3000000",
    organizerFeeMinorUnits: "400000",
    staffFeeBps: "300",
    gtd: monetaryGtd("150000000"),
    startingStack: "40000",
    levelDurationMinutes: ["25", "20"],
    registrationCloseLevel: "11",
    registrationCloseTime: "19:30",
    itmStatement: "25% ITM",
    promotionNote: GRAND_GENERAL_PROMOTION,
    floor: "Level 2",
    visualRegion: "day-1-row-3",
    fieldRegions: { staff_fee_bps: GRAND_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "grand-loyal-mini-high-roller",
    competitionKey: "grand-loyal-event-4-mini-high-roller",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "18:30",
    eventNumber: "4",
    eventName: "Mini High Roller",
    eventFamily: "mini_high_roller",
    prizeContributionMinorUnits: "10000000",
    organizerFeeMinorUnits: "1000000",
    staffFeeBps: "300",
    gtd: monetaryGtd("250000000"),
    startingStack: "100000",
    levelDurationMinutes: ["25", "20"],
    registrationCloseLevel: "9",
    registrationCloseTime: "22:10",
    itmStatement: "15% ITM",
    promotionNote: GRAND_GENERAL_PROMOTION,
    floor: "Level 2",
    visualRegion: "day-1-row-4",
    fieldRegions: { staff_fee_bps: GRAND_STAFF_FEE_REGION },
  }),
  row({
    eventKey: "grand-loyal-s2-kick-off-satellite",
    competitionKey: "grand-loyal-s2-kick-off-satellite",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "19:30",
    eventNumber: "S2",
    eventName: "Satellite - GTD Kick Off Event",
    eventFamily: "satellite",
    prizeContributionMinorUnits: "660000",
    organizerFeeMinorUnits: "140000",
    gtd: seats("5"),
    startingStack: "10000",
    levelDurationMinutes: ["15", "12"],
    registrationCloseLevel: "8",
    registrationCloseTime: "21:25",
    satelliteLinkage: "Madness GTD Kick Off Event",
    promotionNote: GRAND_GENERAL_PROMOTION,
    floor: "Level 3",
    visualRegion: "day-1-row-s2",
  }),
  row({
    eventKey: "grand-loyal-s3-main-event-satellite",
    competitionKey: "grand-loyal-s3-main-event-satellite",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "20:30",
    eventNumber: "S3",
    eventName: "Satellite - Main Event",
    eventFamily: "satellite",
    prizeContributionMinorUnits: "1760000",
    organizerFeeMinorUnits: "340000",
    gtd: seats("3"),
    startingStack: "10000",
    levelDurationMinutes: ["15", "12"],
    registrationCloseLevel: "8",
    registrationCloseTime: "22:25",
    satelliteLinkage: "Main Event",
    promotionNote: GRAND_GENERAL_PROMOTION,
    floor: "Level 3",
    visualRegion: "day-1-row-s3",
  }),
  row({
    eventKey: "grand-loyal-mini-deepstack",
    competitionKey: "grand-loyal-event-5-mini-deepstack",
    sourceId: GRAND_SOURCE,
    scheduleDate: "2026-07-29",
    localStartTime: "21:00",
    eventNumber: "5",
    eventName: "Mini Deepstack",
    eventFamily: "mini_deepstack",
    prizeContributionMinorUnits: "1500000",
    organizerFeeMinorUnits: "300000",
    staffFeeBps: "300",
    gtd: monetaryGtd("15000000"),
    startingStack: "40000",
    levelDurationMinutes: ["20", "15"],
    registrationCloseLevel: "7",
    registrationCloseTime: "23:10",
    itmStatement: "25% ITM",
    promotionNote: GRAND_GENERAL_PROMOTION,
    floor: "Level 2",
    visualRegion: "day-1-row-5",
    fieldRegions: { staff_fee_bps: GRAND_STAFF_FEE_REGION },
  }),
];
